/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
var total;
var tmp;
var fir;
var sec;
total = 2;
fir = 1;
sec = 2;
while ((fir + sec) <= 4000000) {
    tmp = fir + sec;
    if (tmp % 2 == 0) {
        total += tmp;
    }
    fir = sec;
    sec = tmp;
}
console.log(total);
// total = 4613732
